# http://module-build.sourceforge.net/META-spec.html
name:         ExtUtils-FakeConfig
version:      0.12
version_from: lib/ExtUtils/FakeConfig.pm
installdirs:  site
author:       Mattia Barbon <mbarbon@cpan.org>
abstract:     override %Config values on-the-fly
license:      perl
requires:
  File::Spec:    0
  Test::More: 0.48
#build_requires:
no_index:
  directory:
    - t

# extras.
dynamic_config: 1

distribution_type: module
generated_by: ExtUtils::MY_Metafile version 0.09, EUMM-6.44.
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
